### ISSUE TITLE
Support for Contentful?

### ISSUE THREAD

**Issue by janosh** [borgfriend/gatsby-remark-embed-video#11]
I'm using Contentful to grab pages and posts for a website. One page has this markdown:

```
## Heading One

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris placerat finibus enim, ac consequat augue pharetra vel. Nam vulputate sapien in tempus egestas.

`video: https://videos.ctfassets.net/dbpftxjar4kc/4hFiurjbgcC60IaK8MsScM/88f040511911066c625d7875e315a593/wavepump.mp4`

### Heading Two

Curabitur eleifend vehicula quam nec hendrerit. Suspendisse bibendum in tellus sit amet tempus. Aliquam vitae imperdiet libero, id porttitor orci. Suspendisse potenti.
```

I installed and configured `gatsby-remark-embed-video`. It compiles fine but in the browser I just get a red `p` saying `Error: Id could not be processed` where the video should be. Anyway to fix this?

**Comment by alexfornuto** [comment]
I'm getting the same error when trying a video from Wistia:

```
`video: https://fast.wistia.net/embed/iframe/hzsntt6bi2`
```

**Comment by d4rekanguok** [comment]
Hey @janosh ! Have you managed to resolve this issue, or is this still a problem?

**Comment by borgfriend** [comment]
converted this into a feature request #24  - going to start work on it this week

**Comment by janosh** [comment]
@d4rekanguok No I haven't. This is still unresolved.
