### ISSUE TITLE
Uncaught DOMException: Failed to construct 'PresentationRequest': The document is sandboxed and lacks the 'allow-presentation' flag.

### ISSUE THREAD

**Issue by zepa19** [borgfriend/gatsby-remark-embed-video#121]
After update to the 3.1.1 version I got the following error when using the plugin with youtube videos:

```
Uncaught DOMException: Failed to construct 'PresentationRequest': The document is sandboxed and lacks the 'allow-presentation' flag.
```

To solve the issue the `allow-presentation` value needs to be added to the `sandbox` attribute in the iframe. 

Could that attribute be added? Or maybe make a new option, where we would be able to set our own values for that attribute.

**Comment by AlexanderKhudoev** [comment]
I have same issue

**Comment by drwharris** [comment]
@borgfriend can [this](https://github.com/borgfriend/gatsby-remark-embed-video/pull/152) please be merged.

**Comment by borgfriend** [comment]
added support for sandbox option in v3.2.1
