### ISSUE TITLE
Use with gatsby-remark-prismjs

### ISSUE THREAD

**Issue by spences10** [borgfriend/gatsby-remark-embed-video#13]
Hi,

Thanks for this plugin I now have a nice embed, but now no code highlighting 🙃

When I configured Prism more (I was just using the default config) I get this:

![image](https://user-images.githubusercontent.com/234708/48996662-c92c6480-f144-11e8-893c-5ca655c09b83.png)

So it's being treated as inline code now...

Is there a way to use both without them clashing?

**Comment by spences10** [comment]
As a workaround, I have explicitly added languages to the `classPrefix` in `gatsby-remark-prismjs` in an array, like: `classPrefix: ['language-js', 'language-bash']`

I don't think this is a solution though as if you want to use the two together and use many languages you have to define a long list for use in the plugin.

**Comment by d4rekanguok** [comment]
The latest version of this plugin now supports custom markers (i.e using `[[youtube: ...]]` instead of ``` `youtube:...` ```), so it could be a good way to solve this issue:

```
{
    resolve: `gatsby-remark-embed-video`,
    options: {
        beginMarker: `{{`,
        endMarker: `}}`
    }
},
```
