### ISSUE TITLE
Documentation Example Usage not Working

### ISSUE THREAD

**Issue by Twads9816** [borgfriend/gatsby-remark-embed-video#133]
In v4, the markdown usage shown in the documentation:

``youtube: 2Xc9gXyf2G4``

produces:

Error: VideoService could not be found

on the rendered page.

**Comment by hmajid2301** [comment]
I'm pretty sure it used to work anyways for now I've changed syntax from `youtube: 2Xc9gXyf2G4` to `youtube: https://www.youtube.com/watch?v=2Xc9gXyf2G4` and the videos are working again!

**Comment by borgfriend** [comment]
fixed in version 3.1.2
