### ISSUE TITLE
any access to parent div styles?

### ISSUE THREAD

**Issue by ar-stackrox** [borgfriend/gatsby-remark-embed-video#15]
@borgfriend I want to apply this CSS trick for responsive iframes but need to have access to the wrapper div in order to do so. Can you provide a class so i can hook into it? Thanks!

https://blog.theodo.fr/2018/01/responsive-iframes-css-trick/

**Comment by borgfriend** [comment]
I added a wrapper div with the class `embedVideo-container` and the iframe gets the class `embedVideo-iframe` (v1.6.0)
