### ISSUE TITLE
Using with gatsby-mdx

### ISSUE THREAD

**Issue by pszafer** [borgfriend/gatsby-remark-embed-video#20]
Hi,
Thanks for this plugin.
I'm trying to use your plugin with gatsby-mdx.
I have 2 warnings and I'd like to ask if it's something with my config or plugin bug.

gatsby config:
```
resolve: `gatsby-mdx`,
      options: {
        gatsbyRemarkPlugins: [
          {
            resolve: "gatsby-remark-images",
            options: {
              maxWidth: 1035,
              sizeByPixelDensity: true,
              withWebp: true,
              linkImagesToOriginal: false
            }
          },
          {
            resolve: `gatsby-remark-embed-video`,
            options: {
              width: 800,
              height: 400, // Optional: Overrides optional.ratio
              related: false, //Optional: Will remove related videos from the end of an embedded YouTube video.
              noIframeBorder: true //Optional: Disable insertion of <style> border: 0
            }
          }
        ]
      }
    },
```

MDX:
```
---
title: 'text'
---
text

`youtube: someID`

text2
```

Warning 1:
```
index.js:2177 Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
```
Warning 2:
```
Warning: The tag <undefined> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.
```

In the html output I see:
```
<p> <undefined>
        <div class="embedVideo-container">
            <iframe width="800" height="400" src="https://www.youtube.com/embed/id?rel=0" class="embedVideo-iframe" allowfullscreen="" style="border-width: 0px;"></iframe>
        </div></undefined></p>
```

**Comment by TNkemdilim** [comment]
I am also facing this issue...

**Comment by d4rekanguok** [comment]
This does happen when using with mdx, but I can't replicate this issue when using `gatsby-transformer-remark`, so this might be an issue with gatsby-plugin-mdx itself & might be worth it to open an issue over there.

However gatsby-remark-images works fine with mdx, so there _might_ be something we can do to circumvent this issue, though I don't know how yet :(

**Comment by d4rekanguok** [comment]
@borgfriend I diged around a little bit -- the `<undefined>` block is created by `gatsby-remark-responsive-iframe`. This might not be an issue with `gatsby-remark-embed-video`.

**Comment by EllisMin** [comment]
I have managed to resolve the second warning:

`Warning: The tag <undefined> is unrecognized in this browser ...`

 - Error disappeared as I removed an image i.e. `![](../images/image.png)` in a markdown post
 - I realized that the `gatsby-remark-images` did not work as expected with `gatsby-plugin-mdx`

## Solution:
**Include `gatsby-remark-images` under `gatsby-transformer-remark` as well**

```js
    {
      resolve: `gatsby-plugin-mdx`,
      options: {
        extensions: [`.mdx`, `.md`],
        gatsbyRemarkPlugins: [
          {
            resolve: `gatsby-remark-images`,
            options: {
              maxWidth: config.maxWidth,
              backgroundColor: `transparent`,
              linkImagesToOriginal: false,
            },
          },
        ],
      },
    },

  // ... 

    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: `gatsby-remark-images`,
            options: {
              maxWidth: config.maxWidth,
              backgroundColor: `transparent`,
              linkImagesToOriginal: false,
            },
          },
        ],
      },
    },
```

I'm honestly not sure as to why this solves the problem, but I took this approach becuaseI had similar issues with `gatsby-remark-autolink-headers` that needed to be included in both places.

**Comment by borgfriend** [comment]
cannot reproduce this issue with current version of gatsby-plugin-mdx
