### ISSUE TITLE
How to render in html?

### ISSUE THREAD

**Issue by gilbertlucas46** [borgfriend/gatsby-remark-embed-video#21]
I'm using Netlify CMS

![image](https://user-images.githubusercontent.com/5719346/57569341-33507180-7426-11e9-9ecf-f0a52277f198.png)

Now how do you render this in the html?

it's just showing `\`youtube: https://www.youtube.com/embed/RAOd6cSQsr8\``

before I'm just using straight-up iframe from youtube

**Comment by frankcalise** [comment]
You have to toggle the video embed field to markdown to put that code in I believe.

Although I still am having issues with Netlify showing it, it displays the still image with the play button. But then says video unavailable when pressing play.

**Comment by borgfriend** [comment]
Closing issue as I am not sure how to reproduce it and this issue has been inactive.
