### ISSUE TITLE
Add YouTube no-coookie support

### ISSUE THREAD

**Issue by janosh** [borgfriend/gatsby-remark-embed-video#22]
It would be nice if `gatsby-remark-embed-video` respected the _nocookie_ variants of YouTube embeds, i.e.

```md
video: https://youtube-nocookie.com/embed/someVideoId
```

rather than the regular

```md
video: https://youtube.com/embed/someVideoId
```

**Comment by fionawhim** [comment]
I just noticed this as well. Can I make a PR?

**Comment by borgfriend** [comment]
Added support for urloverrides - this should allow you to globally override all youtube links to be embeded via the nocookie links
