### ISSUE TITLE
URL overrides don't appear to be working

### ISSUE THREAD

**Issue by janosh** [borgfriend/gatsby-remark-embed-video#31]
If you take a look at the YouTube embed [on this page](https://studenten-bilden-schueler.de/blog/interview-bayerischer-rundfunk), it's still using the regular URL [despite having specified an override in the site's `gatsby-config`](https://github.com/StudentenBildenSchueler/sbs-homepage/blob/master/gatsby-config.js#L41).

Could this be an implementation issue?

**Comment by janosh** [comment]
This is what the markdown looks like:

```md
Lorem Ipsum

`youtube: wOiAYQeSoF0`
```

**Comment by tibotiber** [comment]
You're missing `options` before `urlOverrides`

```js
  {
    resolve: `gatsby-remark-embed-video`,
    options: {
      urlOverrides: [
        {
          id: `youtube`,
          embedURL: videoId => `https://www.youtube-nocookie.com/embed/${videoId}`,
        },
      ],
    },
  },
```

**Comment by janosh** [comment]
Oops, that's embarassing. 😅

**Comment by tibotiber** [comment]
Haha, we've all been there ;).
