### ISSUE TITLE
Working with gatsby-remark-embed-video + gatsby-remark-responsive-iframe on MDX-posts

### ISSUE THREAD

**Issue by zhandosweb** [borgfriend/gatsby-remark-embed-video#48]
Hello!

I'm using Gatsby MDX plugin to create MDX-posts. 

Now I've installed 2 plugins: gatsby-remark-embed-video and gatsby-remark-responsive-iframe. 

And if I put the following code into MDX-file: `youtube: https://www.youtube.com/watch?v=2Xc9gXyf2G4`, I just see `<code></code>` block. Here is a screenshot: https://prnt.sc/r1g8zj

Please, sir, tell me. Your plugin works with ,mdx-files? Sorry for the noob question.

**Comment by borgfriend** [comment]
adjusted the readme to make this more clear
