### ISSUE TITLE
VM39:20 Component Youtube was not imported, exported, or provided by MDXProvider as global scope MDXDefaultShortcode	@

### ISSUE THREAD

**Issue by benstaf** [borgfriend/gatsby-remark-embed-video#49]
Hi, I tried to embed a video by following the tutorial, but it did not work, in Javascript console I got the error (the only place I got an error message):

`VM39:20 Component Youtube was not imported, exported, or provided by MDXProvider as global scope MDXDefaultShortcode	@
`

**Comment by borgfriend** [comment]
reworked readme to make mdx usage clear
