### ISSUE TITLE
Feature Request: Provide iframe title (A11y Improvement)

### ISSUE THREAD

**Issue by alexfornuto** [borgfriend/gatsby-remark-embed-video#55]
First off, thanks for the plugin! It was a life saver when we first switched to Gatsby and I didn't know a JSX component from a hole in the ground.

[Best practice for accessibility](https://dequeuniversity.com/rules/axe/3.0/frame-title-unique) is to have a unique title for iframes, and my Gatsby-build documentation needs to be accessible. I'm thinking that the syntax to add this could be something like:

```
`video: https://path.to/video "This is the video title"`
```

I'd be happy to help implement this, for what little that's worth (I'm a technical writer not a dev).

Thanks in advance for the attention to this! I'd much prefer this over making another custom component to do the same things plus a title.

**Comment by borgfriend** [comment]
Hmn I would prefer  a syntax more like:
```
`video: [This is the video title](https://path.to/video)`
```
then it would align more to markdown.

I cant promise anything maybe ill have time on the weekend to look into it

**Comment by alexfornuto** [comment]
Any syntax would be fine with me - I ended up making a custom component to resolve accessibility for my instance, but this is still a worthwhile effort for others, to increase accessibility coverage. I could also switch back to the plugin to help test/debug this feature.

**Comment by borgfriend** [comment]
added mechanism with new syntax

**Comment by alexfornuto** [comment]
@borgfriend Thanks! For anyone else brought here by Google in the future, [here's the change to documentation](https://github.com/borgfriend/gatsby-remark-embed-video/commit/051c569ca6fe4a9834780d5957422e5b9bba60e5).
