### ISSUE TITLE
Twitch Embedded Video Support

### ISSUE THREAD

**Issue by brandonkal** [borgfriend/gatsby-remark-embed-video#9]
This would be a nice feature to have

**Comment by borgfriend** [comment]
I am not familiar with twitch, however I took a quick look at the site and found two different types of embeddable content: streams and videos.

**Streams:**
https://www.twitch.tv/<channelName>
https://player.twitch.tv/?channel=<channelName>

**Videos**
https://www.twitch.tv/video/<VideoId>
https://player.twitch.tv/?autoplay=false&video=v<VideoId>

If you have more documentation I am happy to add the other types of links.

**Comment by brandonkal** [comment]
At least for me, video embedding would be most useful.

Here are some sample embed codes for streams:

```
<iframe src="https://www.twitch.tv/embed/eleaguetv/chat" frameborder="0" scrolling="no" height="500" width="350"></iframe>

<iframe src="https://www.twitch.tv/embed/legionmofficial/chat" frameborder="0" scrolling="no" height="500" width="350"></iframe>
```

And an embed code for a video highlight:
```
<iframe src="https://player.twitch.tv/?autoplay=false&video=v237083291" frameborder="0" allowfullscreen="true" scrolling="no" height="378" width="620"></iframe>
```

In the case of streams, the only real variable is the channel name.
In the case of video highlights, the numerical video ID changes between videos.

Here's the video url for the example above:
https://www.twitch.tv/videos/237083291

Doing something like this should be possible:
```
twitch: 237083291
OR
twitch: https://www.twitch.tv/videos/237083291
```

Because video IDs are only numeric, it should be possible to detect whether the parameter is a channel or a a video, though it could just be `twitch-live:` for instance.
