### ISSUE TITLE
Build warning: Error persisting state. 

### ISSUE THREAD

**Issue by PaulBunker** [borgfriend/gatsby-remark-embed-video#93]
Hi, 

I get the following error when building.

```
warning Error persisting state: function plugin({ 
  beginMarker,
  endMarker,
  pattyName = 'patty',
  onlyRunWithMarker = false, 
  insertBef...<omitted>...
} could not be cloned.
```

I have tracked down the code from the error message to `remark-burger` which is only imported by `gatsby-remark-embed-video` in my project.

**Comment by cameronbraid** [comment]
I ran into the same problem.  It prevents the gatsby build .cache from being used :(

**Comment by mschel** [comment]
Are there any news on this one?

**Comment by borgfriend** [comment]
Can you provide some more information on how to reproduce this? Is this still a problem?

**Comment by cameronbraid** [comment]
I must have found a workaround or an alternative and at this point I can't remember what I did.

**Comment by mschel** [comment]
If you use the mentioned Plugin and have a MDX File with is processed you will see the warning in Logs
