### ISSUE TITLE
Error Persisting State

### ISSUE THREAD

**Issue by tnorlund** [borgfriend/gatsby-remark-embed-video#95]
So I'm getting this error while developing and building Gatsby.

```
warning Error persisting state: function plugin({ 
  beginMarker,
  endMarker,
  pattyName = 'patty',
  onlyRunWithMarker = false, 
  insertBef...<omitted>...
} could not be cloned.
```

This comes from the remark-burger dependency. Is there a way to remove this warning?

**Comment by aeneasr** [comment]
Just wanted to drop in that we also observe this issue!

**Comment by tnorlund** [comment]
Alright cool. Can I help out with anything?

**Comment by aeneasr** [comment]
I think the problem is related to the gatsby mdx transformer!

**Comment by JasonWang258** [comment]
I removed the error message by adding the following to gatsby-plugin-mdx setting:
        ```remarkPlugins: [
          require('remark-burger')
        ],```

**Comment by tnorlund** [comment]
@JasonWang258 This worked.
